[settings]
# A unique string identifying this type of bot, typically on the form "<developer>/<botname>"
# VVVVV CHANGE THIS VVVVV
agent_id = "codered/redbot"
# The name that will be displayed in game
name = "RedBot"
# Path to loadout config from runner
loadout_file = "Loadout.toml"
# (OPTIONAL) - what you want the working directory set to
# This is relative to the location of this file
root_dir = ""
# The command RLBot will call to start your bot on Windows
# ex: "bot.exe" for after your bot is compiled (via `dotnet publish`), or `dotnet run`/`dotnet run -c "Release"` during development
run_command = ".\\Bot\\bin\\Debug\\net8.0\\Bot.exe"
# The command RLBot will call to start your bot on linux
# If this isn't set, RLBot may attempt to run the Windows command under Wine
# run_command_linux = "dotnet run --project ./Bot -c \"Release\""

[details]
description = "A bot made with RedUtils!"
fun_fact = "Currently a ball chaser. It will never let go of the ball, EVER!"
source_link = "https://github.com/RLBot/RLBot"
developer = "CodeRed"
language = "C#"
# ALL POSSIBLE TAGS: 1v1, teamplay, goalie, hoops, dropshot, snow-day, spike-rush, heatseaker, memebot
# NOTE: Only add the goalie tag if your bot only plays as a goalie; this directly contrasts with the teamplay tag!
# NOTE: Only add a tag for a special game mode if you bot properly supports it
tags = []
